### ISSUE TITLE
Shelf support

### ISSUE THREAD

**Issue by Liiw** [zach2039/vs-beehivekiln#5]
Hello!

Great mod! I'm currently playing on 1.18.15 and the kiln is working fine. However would it be possible to implement shelf support? I tested by placing bowl on double shelves and unfortunately they remained raw after the firing was complete. The stuff on the floor fired well, but items on shelves did not.

**Comment by VaelophisNyx** [comment]
Shelves would be neat though making specific ceramic shelves would probably be best imo
