### ISSUE TITLE
Beehive kiln flue and grating are ? blocks

### ISSUE THREAD

**Issue by VaelophisNyx** [zach2039/vs-beehivekiln#6]
![image](https://github.com/zach2039/vs-beehivekiln/assets/1534478/0e9cb586-ae92-4ea8-b281-bf22faa26cbc)
![image](https://github.com/zach2039/vs-beehivekiln/assets/1534478/4f70b75d-f295-4588-b6ca-1208ef51ee92)
This is after updating to 1.5.3 (the change in 1.5.4 isn't useful to my server so we didn't grab it). They also don't appear in the handbook at all

relevant error:
`29.4.2024 14:59:39 [Error] [beehivekiln_1.5.3.zip] An exception was thrown trying to to load the ModInfo:
29.4.2024 14:59:39 [Error] [beehivekiln_1.5.3.zip] Exception: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name, StringCodec stringCodec)
   at Vintagestory.Common.ModContainer.LoadModInfo(ModCompilationContext compilationContext, ModAssemblyLoader loader) in VintagestoryLib\Common\API\ModContainer.cs:line 344`

full log:
[server-main.txt](https://github.com/zach2039/vs-beehivekiln/files/15154736/server-main.txt)

**Comment by zach2039** [comment]
Check the contents of beehivekiln_1.5.3.zip if you would. I had an issue with modDB when trying to replace the zip on the v1.5.3 release and I had to reupload. The bad zip version will be empty.

**Comment by zach2039** [comment]
Cause was corrupted zip file on modDB. Was resolved when release for v1.5.3 was recreated with new zip.
